const roles={
 important:[
  ['Adrian','Adriana','Arden','The Heir / Heredero/a'],['Lucien','Lucienne','Lux','The Treasurer / Tesorero/a'],['Oliver','Ophelia','Onyx','The Medium / Médium'],['Victor','Victoria','Valentine','The Physician / Médico/a'],['Sebastian','Seraphina','Salem','The Archivist / Archivista'],['Dorian','Dahlia','Darcy','The Attorney / Abogado/a'],['Theodore','Theodora','Theo','The Professor / Profesor/a'],['Nicholas','Nicolette','Nico','The Investigator / Investigador/a'],['Alexander','Alexandra','Alex','The Socialite / Socialité'],['Vincent','Vivienne','Vesper','The Apothecary / Boticario/a'],['Edmund','Edith','Eden','The Historian / Historiador/a'],['Marcus','Marcella','Mars','The Journalist / Periodista'],['Gabriel','Gabriella','Gray','The Collector / Coleccionista'],['Henry','Helena','Hollis','The Groundskeeper / Jardinero/a'],['Roman','Romina','Rowan','The Exile / Exiliado/a'],['Felix','Felicity','Fable','The Confidant / Confidente']],
 supporting:[['Julian','Juliette','Jules','The Artist / Artista'],['Maxwell','Maxine','Max','The Rival / Rival'],['August','Augusta','Avery','The Benefactor / Benefactor/a'],['Casper','Cassandra','Cass','The Fortune Teller / Adivino/a']],
 walkin:[['Milo','Mila','Morgan','The Photographer / Fotógrafo/a'],['Arthur','Artemis','Ari','The Librarian / Bibliotecario/a'],['Percival','Persephone','Perry','The Entertainer / Artista de variedades'],['Benjamin','Beatrice','Blair','The Caterer / Responsable del banquete'],['Thomas','Talia','Taylor','The Newcomer / Recién llegado/a']]
};
function poolFor(a,d){if(a==='unknown'||d==='unknown'||['2030','2100'].includes(a)||d==='2200')return'walkin';if(['1830','1900','1915'].includes(a)&&['0000','0100','late'].includes(d))return'important';return'supporting'}
function chosenName(r,p){return r[p==='m'?0:p==='f'?1:2]}
function assign(pool,presentation){const used=JSON.parse(localStorage.getItem('crowUsed')||'[]');let available=roles[pool].filter(r=>!used.includes(r[3]));if(!available.length)available=roles[pool];const role=available[Math.floor(Math.random()*available.length)];used.push(role[3]);localStorage.setItem('crowUsed',JSON.stringify(used));return {name:chosenName(role,presentation),role:role[3],pool}}
const form=document.getElementById('rsvpForm'),details=document.getElementById('attendanceDetails'),result=document.getElementById('result');
form.addEventListener('change',e=>{if(e.target.name==='attending')details.style.opacity=e.target.value==='no'?'.35':'1'});
form.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form),att=f.get('attending');if(att==='no'){result.hidden=false;result.innerHTML='<h3>Your reply has been received.</h3><p>You will be missed at the gathering.</p>';return}const pool=poolFor(f.get('arrival'),f.get('departure')),a=assign(pool,f.get('presentation'));const record={guest:f.get('guestName'),contact:f.get('contact'),attending:att,arrival:f.get('arrival'),departure:f.get('departure'),presentation:f.get('presentation'),timingNotes:f.get('timingNotes'),diet:f.get('diet'),assignment:a,created:new Date().toISOString()};const rs=JSON.parse(localStorage.getItem('crowRSVPs')||'[]');rs.push(record);localStorage.setItem('crowRSVPs',JSON.stringify(rs));result.hidden=false;result.innerHTML=`<p class="kicker">The Order has received your reply</p><h3>${record.guest}, your place has been recorded.</h3><p class="assignment">${a.name}<br><small>${a.role}</small></p><p>Your full character materials and supernatural species will be revealed at the gathering. Please keep this assignment private.</p><p><small>Assignment pool: ${a.pool==='important'?'full-investigation':a.pool==='supporting'?'supporting':'late-arrival / flexible'}.</small></p>`;result.scrollIntoView({behavior:'smooth'});});